# From https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#creating-automatically-generated-release-notes-for-a-new-release
changelog:
  categories:
    - title: 🐛 Fixes / 🚀 Enhancements
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 👒 Project Dependencies
      labels:
        - java
    - title: 👒 CI Dependencies
      labels:
        - github_actions
