/**
 * JBoss, Home of Professional Open Source.
 * Copyright 2014 Red Hat, Inc., and individual contributors
 * as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.pnc.model;

import org.hibernate.annotations.ForeignKey;
import org.hibernate.annotations.Index;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * JPA entity representing the artifacts generated by a build (build output).  
 * Each artifact is mapped to a single build which produced the artifact.
 * 
 */
@Entity
public class BuiltArtifact extends Artifact {

    private static final long serialVersionUID = 1L;


    /**
     * The build record of the build which produced this artifact
     */
    @NotNull
    @ManyToOne
    @ForeignKey(name = "fk_artifact_buildrecord")
    @Index(name="idx_artifact_buildrecord")
    @Column(updatable=false)
    private BuildRecord buildRecord;

    /**
     * Instantiates a new artifact.
     */
    public BuiltArtifact() {
    }

    /**
     * Gets the project build record.
     *
     * @return the project build record
     */
    public BuildRecord getBuildRecord() {
        return buildRecord;
    }

    /**
     * Sets the project build record.
     *
     * @param buildRecord the new project build record
     */
    public void setBuildRecord(BuildRecord buildRecord) {
        this.buildRecord = buildRecord;
    }

    /*
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        Integer buildRecordId = (getBuildRecord()==null)?null:getBuildRecord().getId();
        return "Built Artifact [id: " + getId() + ", produced by build id:" + buildRecordId + "]";
    }

    public static class Builder extends Artifact.Builder {

        private Integer id;

        private String identifier;

        private RepositoryType repoType;

        private String checksum;

        private String filename;

        private String deployUrl;

        private ArtifactStatus status;

        private Set<BuildRecord> dependantBuildRecords;

        private BuildRecord buildRecord;

        public Builder() {
            dependantBuildRecords = new HashSet<BuildRecord>();
        }

        public static Builder newBuilder() {
            return new Builder();
        }

        public BuiltArtifact build() {
            BuiltArtifact artifact = new BuiltArtifact();
            artifact.setId(id);
            artifact.setIdentifier(identifier);
            artifact.setRepoType(repoType);
            artifact.setChecksum(checksum);
            artifact.setFilename(filename);
            artifact.setDeployUrl(deployUrl);
            artifact.setStatus(status);
            if (dependantBuildRecords != null) {
                artifact.setDependantBuildRecords(dependantBuildRecords);
            }
            artifact.setBuildRecord(buildRecord);

            return artifact;
        }

        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        public Builder identifier(String identifier) {
            this.identifier = identifier;
            return this;
        }

        @Deprecated
        public Builder repoType(RepositoryType repoType) {
            this.repoType = repoType;
            return this;
        }

        public Builder checksum(String checksum) {
            this.checksum = checksum;
            return this;
        }

        public Builder filename(String filename) {
            this.filename = filename;
            return this;
        }

        public Builder deployUrl(String deployUrl) {
            this.deployUrl = deployUrl;
            return this;
        }

        public Builder status(ArtifactStatus status) {
            this.status = status;
            return this;
        }

        public Builder dependantBuildRecords(Set<BuildRecord> dependantBuildRecords) {
            this.dependantBuildRecords = dependantBuildRecords;
            return this;
        }

        public Builder buildRecord(BuildRecord buildRecord) {
            this.buildRecord = buildRecord;
            return this;
        }

    }
}
