<?xml version="1.0" encoding="UTF-8"?>
<!--

    SPDX-FileCopyrightText: Copyright © 2014 Red Hat, Inc., and individual contributors as indicated by the @author tags.
    SPDX-License-Identifier: Apache-2.0

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.jboss.pnc</groupId>
    <artifactId>parent</artifactId>
    <version>3.6.0-SNAPSHOT</version>
  </parent>

  <artifactId>rest-client-jakarta</artifactId>
  <name>rest-client-jakarta</name>

  <dependencies>
    <dependency>
      <groupId>org.jboss.pnc</groupId>
      <artifactId>rest-client</artifactId>
      <version>${project.version}</version>
      <classifier>jakarta</classifier>
      <exclusions>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>rest-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>dto</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>pnc-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>pnc-common</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.jboss.pnc</groupId>
      <artifactId>rest-api</artifactId>
      <version>${project.version}</version>
      <classifier>java-client-jakarta</classifier>
      <exclusions>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>dto</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>pnc-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.jboss.pnc</groupId>
      <artifactId>dto</artifactId>
      <version>${project.version}</version>
      <classifier>patch-builders-jakarta</classifier>
      <exclusions>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>pnc-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.jboss.pnc</groupId>
      <artifactId>common</artifactId>
      <version>${project.version}</version>
      <classifier>jakarta</classifier>
      <exclusions>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>pnc-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>pnc-common</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.jboss.pnc</groupId>
      <artifactId>pnc-common</artifactId>
      <version>${version.pnc-common}</version>
      <classifier>jakarta</classifier>
      <exclusions>
        <exclusion>
          <groupId>org.jboss.pnc</groupId>
          <artifactId>pnc-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.jboss.pnc</groupId>
      <artifactId>pnc-api</artifactId>
      <version>${version.pnc-api}</version>
      <classifier>jakarta</classifier>
    </dependency>

    <!-- Needed to be able to fetch jakarta version of JacksonJsonProvider in JacksonProviderWithDateISO8601 -->
    <dependency>
      <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
      <artifactId>jackson-jakarta-rs-json-provider</artifactId>
    </dependency>
  </dependencies>
</project>
