name: Mend CLI scan for Maven

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 22 * * 0"

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  security-events: write

jobs:
  build:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-ci.yml@a27e6fba6b28bbb96881ec096e9c8ea5a538f481 # v0.0.22
    with:
      java_version: 11
      build_command: "mvn clean install -DskipTests"
      upload_artifacts: true

  call-mend-ci:
    needs: build
    uses: project-ncl/shared-github-actions/.github/workflows/mend-ci.yml@a27e6fba6b28bbb96881ec096e9c8ea5a538f481 # v0.0.22
    with:
      project_name: 'project-ncl/pnc'
      SCA: true
      SAST: true
      SCA_EXCLUDES: "test-common/**,pnc-mock/**,integration-test/**,integration-test-rex/**"
      SAST_EXCLUDES: "test-common/,pnc-mock/,integration-test/,integration-test-rex/"
    secrets:
      MEND_URL: ${{ secrets.MEND_URL }}
      MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
      MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
      MEND_ORGNAME: ${{ secrets.MEND_ORGNAME }}
      MEND_PRODUCTNAME: ${{ secrets.MEND_PRODUCTNAME }}
