name: Java CI with Maven

permissions:
  contents: read

on:
  pull_request:
    branches: ["*"]

jobs:
  call-maven-ci:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-ci.yml@dc16c38747e72ec04165d5e5e0177e85d21bc5c8 # main
    with:
      java_version: 11
      build_command: "mvn clean install -DskipTests"
      upload_artifacts: true
