name: Mend CLI scan for Maven PR

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: ["Java CI with Maven"]
    types: [completed]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  security-events: write

concurrency:
  group: mend-scan-${{ github.event.workflow_run.pull_requests[0].number || github.event.workflow_run.head_sha }}
  cancel-in-progress: true

jobs:
  scan:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    uses: project-ncl/shared-github-actions/.github/workflows/mend-ci.yml@dc16c38747e72ec04165d5e5e0177e85d21bc5c8 # main
    with:
      SCA: true
      SAST: true
      triggering_run_id: ${{ github.event.workflow_run.id }}
      pr_feedback: true
    secrets:
      MEND_URL: ${{ secrets.MEND_URL }}
      MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
      MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
      MEND_ORGNAME: ${{ secrets.MEND_ORGNAME }}
      MEND_PRODUCTNAME: ${{ secrets.MEND_PRODUCTNAME }}
