name: Validate GitHub Actions Workflows
permissions: {}

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:

  validate:
    uses: project-ncl/shared-github-actions/.github/workflows/validate-gh-action.yml@f7041589cc1ce5e75564bda958cc6e5182c240cd # v0.0.15
